// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	login.proto

It has these top-level messages:
	LoginReq
	LoginResp
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginReq struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Version  int32  `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginReq) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type LoginResp struct {
	Result       int32  `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Username     string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Uid          uint32 `protobuf:"varint,3,opt,name=uid" json:"uid,omitempty"`
	Token        string `protobuf:"bytes,4,opt,name=token" json:"token,omitempty"`
	ExpiresIn    string `protobuf:"bytes,5,opt,name=expires_in,json=expiresIn" json:"expires_in,omitempty"`
	RefreshToken string `protobuf:"bytes,6,opt,name=refresh_token,json=refreshToken" json:"refresh_token,omitempty"`
}

func (m *LoginResp) Reset()                    { *m = LoginResp{} }
func (m *LoginResp) String() string            { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()               {}
func (*LoginResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginResp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *LoginResp) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginResp) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *LoginResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResp) GetExpiresIn() string {
	if m != nil {
		return m.ExpiresIn
	}
	return ""
}

func (m *LoginResp) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginReq)(nil), "pb.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "pb.LoginResp")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4a, 0xc5, 0x30,
	0x10, 0x45, 0x49, 0x9f, 0xa9, 0xaf, 0xa3, 0x0f, 0x24, 0x88, 0x04, 0x41, 0x28, 0x75, 0xd3, 0x95,
	0x1b, 0xbf, 0x42, 0x70, 0x15, 0x5c, 0x0a, 0xa5, 0xa5, 0xa3, 0x06, 0x6b, 0x12, 0x67, 0x5a, 0xf5,
	0x9f, 0xfc, 0x49, 0x49, 0x9a, 0x0a, 0xba, 0xcb, 0x39, 0x77, 0x72, 0x07, 0x06, 0x4e, 0x26, 0xff,
	0x6c, 0xdd, 0x4d, 0x20, 0x3f, 0x7b, 0x55, 0x84, 0xa1, 0x79, 0x84, 0xfd, 0x7d, 0x54, 0x06, 0xdf,
	0xd5, 0x25, 0xec, 0x17, 0x46, 0x72, 0xfd, 0x1b, 0x6a, 0x51, 0x8b, 0xb6, 0x32, 0xbf, 0x1c, 0xb3,
	0xd0, 0x33, 0x7f, 0x7a, 0x1a, 0x75, 0xb1, 0x66, 0x1b, 0x2b, 0x0d, 0xc7, 0x1f, 0x48, 0x6c, 0xbd,
	0xd3, 0xbb, 0x5a, 0xb4, 0xd2, 0x6c, 0xd8, 0x7c, 0x0b, 0xa8, 0x72, 0x3d, 0x07, 0x75, 0x01, 0x25,
	0x21, 0x2f, 0xd3, 0x9c, 0xda, 0xa5, 0xc9, 0xf4, 0x67, 0x6f, 0xf1, 0x6f, 0xef, 0x19, 0xec, 0x16,
	0x3b, 0xa6, 0xde, 0x83, 0x89, 0x4f, 0x75, 0x0e, 0x72, 0xf6, 0xaf, 0xe8, 0xf4, 0x51, 0x1a, 0x5d,
	0x41, 0x5d, 0x01, 0xe0, 0x57, 0xb0, 0x84, 0xdc, 0x59, 0xa7, 0x65, 0x8a, 0xaa, 0x6c, 0xee, 0x9c,
	0xba, 0x86, 0x03, 0xe1, 0x13, 0x21, 0xbf, 0x74, 0xeb, 0xe7, 0x32, 0x4d, 0x9c, 0x66, 0xf9, 0x10,
	0xdd, 0x50, 0xa6, 0xb3, 0xdc, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x4b, 0xee, 0x78, 0x25,
	0x01, 0x00, 0x00,
}
